# Docker Compose for the Dockerfile
Linky:
  Image: linky
  Ports:
    - "12921:8000"
  Volumes:
    - ${PWD}/database.db:/app/url.db
  Environment:
    - LINKY_PASSWORD = # Your password here
    - LINKY_SITE_URL = # Your site url here