# Docker Compose for the Dockerfile
version: '3.3'
services:
  Linky:
    image: linky
    build:
        context: ./   
        dockerfile: Dockerfile
    Ports:
      - "80:8000"
    Volumes:
      - ${PWD}/database.db:/app/linky.db
    Environment:
      - LINKY_SECRET_KEY = # Your password here
      - LINKY_SITE_URL = # Your site url here